name: Ensure App Registration Dispatch
run-name: ${{ github.event.action }}:${{ github.event.client_payload.dispatch_job_id }}

on:
  repository_dispatch:
    types: [ensure-app-registration]

jobs:
  perform-service-operation:
    runs-on: windows-latest

    steps:
    - name: "OnfusionCoE: Ensure Security Group Dispatch"
      uses: fusioncoe/onfusioncoe-actions-g2/ensure-app-registration@v0
      with:
        client_id: ${{ vars.FUSIONCOE_SP_APPLICATION_ID }}
        client_secret: ${{ secrets.FUSIONCOE_SP_SECRET }}
        tenant_id: ${{ vars.FUSIONCOE_SP_TENANT_ID }}
        authority: ${{ vars.FUSIONCOE_SP_AUTHORITY }}        
        cloud: ${{ vars.FUSIONCOE_SP_CLOUD }}    
