name: FusionCoE Service Operations

on:
  repository_dispatch:
    types: [service-admin-operation]

jobs:
  perform-service-operation:
    runs-on: windows-latest

    steps:
    - name: "OnfusionCoE: General Service Dispatch"
      uses: fusioncoe/onfusioncoe-actions-g2/process-service-repo-dispatch@v0
      with:
        client_id: ${{ vars.FUSIONCOE_SP_APPLICATION_ID }}
        client_secret: ${{ secrets.FUSIONCOE_SP_SECRET }}
        tenant_id: ${{ vars.FUSIONCOE_SP_TENANT_ID }}
        authority: ${{ vars.FUSIONCOE_SP_AUTHORITY }}        
        cloud: ${{ vars.FUSIONCOE_SP_CLOUD }}